### ISSUE TITLE
Fix "TODO" issue in handlers/message.go

### ISSUE THREAD

**Issue by JustAnotherOrganizationGit** [JustAnotherOrganization/tiberious#31]
TODO found

https://codeclimate.com/github/JustAnotherOrganization/tiberious/handlers/message.go#issue_570555aaa4db6100017b9d54

**Comment by IngCr3at1on** [comment]
@GrimTheReaper line 67;  that's pretty much a question for you :P

**Comment by IngCr3at1on** [comment]
Replaced in v2 branch.
