### ISSUE TITLE
Fix "TODO" issue in handlers/clienthandler.go

### ISSUE THREAD

**Issue by JustAnotherOrganizationGit** [JustAnotherOrganization/tiberious#44]
TODO found

https://codeclimate.com/github/JustAnotherOrganization/tiberious/handlers/clienthandler.go#issue_57903e99dc6149000105b862

**Comment by IngCr3at1on** [comment]
https://github.com/JustAnotherOrganization/tiberious/blob/master/handlers/clienthandler.go#L181

**Comment by IngCr3at1on** [comment]
Replace in v2 branch
