### ISSUE TITLE
Slack or gitter or other chat for discussions?

### ISSUE THREAD

**Issue by jeremywho** [JustAnotherOrganization/tiberious#49]
I'm just wondering if there is anything setup to talk about the project?

**Comment by IngCr3at1on** [comment]
@jeremywho we have a slack instance setup yes, I'm not sure off the top of my head how to invite people to it; @GrimTheReaper can probably add you though.

**Comment by GrimTheReaper** [comment]
@jeremywho I'll invite you to the slack group once I fix the channels. What is your email?

**Comment by jeremywho** [comment]
jeremy@weebu.com

do you have the slack subdomain name?  I think I can just signup from there. ie [name].slack.com

thanks!

**Comment by GrimTheReaper** [comment]
Added. If anyone else wants to join please post here. Closing as it is now resolved.
