### ISSUE TITLE
Tiberious doesn't have a license

### ISSUE THREAD

**Issue by GrimTheReaper** [JustAnotherOrganization/tiberious#55]
@IngCr3at1on What are your thoughts on adding a license?

**Comment by IngCr3at1on** [comment]
For some reason I thought we added one at one point... It definitely needs one yes.

**Comment by GrimTheReaper** [comment]
[Apache](https://www.apache.org/licenses/LICENSE-2.0) :P

**Comment by IngCr3at1on** [comment]
Just for that! https://www.youtube.com/watch?v=vQObWW06VAM

**Comment by IngCr3at1on** [comment]
Seriously though, I guess that would be alright. I just hate when people abuse it like we were discussing earlier.
